# Site settings
title: GMR Blog
SEOTitle: GMR Blog | GMR Blog
header-img: img/ESW-bg.jpeg
email: gustavomarti007@gmail.com
description: "这里是 @Hux黄玄 的个人博客，与你一起发现更大的世界 | 要做一个有 swag 的程序员"
keyword: "Artificial Inteligence, Gustavo M.R., Hux, 鬼栈, huxpro, @huxpro, 黄玄的博客, Hux Blog, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 前端, 设计"
url: "https://gustavomartins-github.github.io/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username: huxpro
# zhihu_username: huxpro
github_username: gustavomartins-github
twitter_username: lxgustxl
facebook_username:  lxgustxl
linkedin_username: gustavo-martins-089a14201

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: lxgustxl

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Gustavo Martins Ribeiro <br> Software Engineering Student <br> UNB FGA"
sidebar-avatar: https://github.com/gustavomartins-github.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "Gabriel F. da Silva", href: "https://github.com/oo7gabriel" },
    { title: "Pedro Vitor Augusto de Jesus", href: "https://github.com/Peedrooo" },
    { title: "Siqueira", href: "https://github.com/siqueira-dev" },
    { title: "Mateus Moreira", href: "https://github.com/mateus-lm" },
    { title: "Delziron Braz", href: "https://github.com/DelzironBraz" } 
  ]
